SSDProject/nand.cpp
SSDProject/nand.h
SSDProject/nand_test.cpp
SSDProject/ssd.cpp
SSDProject/ssd.h
SSDProject/ssd_test.cpp

SSDProject를 위한 파일을 생성합니다.
리뷰 부탁드립니다.

[#3][Feature] Create files in SSDProject

---

.github/ISSUE_TEMPLATE/feature.md

[#5][Git] Update Issue Template

---

SSDProject/SSDProject.vcxproj
SSDProject/SSDProject.vcxproj.filters
SSDProject/main.cpp
SSDProject/nand.cpp
SSDProject/nand.h
SSDProject/nand_test.cpp

Nand Class 설계 및 Read 중 예외처리를 하는 함수를 구현합니다.
Read/write 예외처리 구현 이후 Read /write에 대한 상세한 동작을 구현하겠습니다.

[#10][TDD-GREEN] Nand Class 설계 및 Read/Write 함수 기본 구현

---

TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/shell.cpp
TestShell/shellInterface_test.cpp

- #29
- [TDD_RED] TDD__RED 를 위한 basic PR 입니다.
- [*] TestShell
- shell_test 의 TC 1 추가하고, input, output 을 fake로 검사했습니다.

29 tdd red add input command for testshell

---

TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/testScript.cpp
TestShell/testScript.h
TestShell/testScript_test.cpp

- #40 
- #46 
- [TDD] <<1_FullWriteAndReadCompare>> phase 1 - Add FullWriteAndReadCompare()
- [ x ] TestScript
- Add Throw Invalid Test TCs
- Add FullWriteAndReadCompare()

[TDD] <<1_FullWriteAndReadCompare>> phase 1 - Add FullWriteAndReadCompare()

---

SSDProject/nand.h
SSDProject/ssd.cpp
SSDProject/ssd.h
SSDProject/ssd_test.cpp

- #27 
- [TDD_Green] SSD class 생성 및 구현, SSD 단일 검증 UT 구현
- SSD class 생성 및 구현 (Read, Write)
- SSD 단일 검증을 위한 Mock 이용한 UT 구현

[TDD_RED, GREEN] 13 red create ssd class add ut

---

SSDProject/nand.cpp
SSDProject/nand.h
SSDProject/nand_test.cpp

- #35
- [PREFIX] [#35][TDD_Red/Green] Read After Write 가능 및 TC 추가
-Read After Write가 될 수 있도록 설정합니다.
- ssd_nand.txt 파일을 통해 data를 read하고 write 할 수 있는 기능을 추가합니다.

[#35][TDD_Red/Green] Read After Write 가능 및 TC 추가

---

SSDProject/SSDProject.vcxproj
SSDProject/SSDProject.vcxproj.filters
SSDProject/global_config.h
SSDProject/nand.cpp
SSDProject/nand.h
SSDProject/nand_test.cpp
SSDProject/ssd.cpp
SSDProject/ssd.h
SSDProject/ssd_test.cpp

- #55 
- [PREFIX] [#55][Refactor] SSD/NAND Glogbal Config 추가 및 NAND/SSD 코드 형식대로 수정 진행
- global config를 만들어서, LBA/ DATA를 SSD, NAND에서 명시적으로 구분하여 사용할 수 있도록 코드를 리팩토링합니다.

[#55][Refactor] SSD/NAND Glogbal Config 추가 및 NAND/SSD 코드 형식대로 수정 진행

---

TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/commandParser.cpp
TestShell/executor.cpp
TestShell/executor_test.cpp
TestShell/interface.h

- 이 PR이 해결하는 이슈 번호를 적어주세요. 예: `#123`
#34
- [PREFIX] PR 제목을 간결하게 작성해주세요.
add mockSddApp to executor test code
Test를 좀더 보강하기 위한 MockSddApp 추가했습니다.

[#34][TDD][RED/GREEN] add mockSddApp to executor test code

---

SSDProject/global_config.h
SSDProject/nand.h
SSDProject/ssd.cpp
SSDProject/ssd.h
SSDProject/ssd_test.cpp

- #51 
- SSD Class
- 중복 코드 및 가독성 개선을 위한 함수화
- SSD UT
- Mock 에러 메세지 제거를 위해 Nice Mock으로 변경
- Test Fixture 추가
- 중복 변수 const로 선언
- 중복 동작 함수화

[#51][REFACTOR] SSD class, UT Refactoring

---

TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/commandParser.cpp
TestShell/executor.cpp
TestShell/shell.cpp
TestShell/shellInterface_test.cpp

- #45
- [TDD] add writeandexit readandexit
- mock을 사용하여 writeandexit readandexit 까지만 TC 를 추가했습니다.

[#45][TDD_GREEN] test_shell: add writeandexit readandexit helpandexit tc

---

SSDProject/global_config.h
SSDProject/ssd.cpp
SSDProject/ssd.h
SSDProject/ssd_test.cpp

- #66 
- Invalid LBA Case UT 수정
- Invalid param case에 대한 처리 코드를 교안에 맞게 수정

[#67][TDD_GREEN] invalid param case에 대한 처리 수정

---

TestShell/shellInterface_test.cpp

- #72
- [TDD_REFACTOR] add GetResultFromShellLoop
- add GetResultFromShellLoop

[#72][TDD_REFACTOR] add GetResultFromShellLoop

---

SSDProject/global_config.h
SSDProject/nand.cpp
SSDProject/nand.h
SSDProject/ssd.cpp
SSDProject/ssd.h
SSDProject/ssd_test.cpp

- (리뷰 반영) include 위치 fix
- #70 
-  리뷰 반영
- include 위치 global_config.h 로 이동

[#70][TDD_REFACTOR] invalid param case에 대한 처리 코드를 교안에 맞게 수정

---

TestShell/testScript.cpp
TestShell/testScript.h
TestShell/testScript_test.cpp

- #52 
- #54 
- [TDD]<<1_FullWriteAndReadCompare>> phase 2 - Implement to call writer and reader
- [Bugfix] Fix invalid check status
- [#52][TDD_Red]<<1_FullWriteAndReadCompare>> phase 2 - Add to Check Read and Write times TC
- [#54][TDD_Green]<<1_FullWriteAndReadCompare>> phase 2 - Implement to call writer and reader

[TDD]<<1_FullWriteAndReadCompare>> phase 2 - Implement to call writer and reader

---

TestShell/commandParser.cpp
TestShell/commandParser.h
TestShell/executor.cpp
TestShell/executor.h
TestShell/shell.cpp
TestShell/shellInterface_test.cpp

- #75
- [#75][TDD] add help command
- help command TC 추가했습니다.

[#75][TDD] add help command

---

TestShell/testScript.cpp
TestShell/testScript.h
TestShell/testScript_test.cpp

- #89 
- #90 
- #91 
- [TDD]<<2_PartialLBAWrite>> phase 1 - Implement PartialLBAWrite()
- [#89][TDD_Red]<<2_PartialLBAWrite>> phase 1 - Add Throw and CheckReadandWriteTimes TCs
- [#90][TDD_Green]<<2_PartialLBAWrite>> phase 1 - Implement PartialLBAWrite()
- [#91] [TDD_Refactor]<<2_PartialLBAWrite>> phase 1 - Re-define Const

[TDD]<<2_PartialLBAWrite>> phase 1 - Implement PartialLBAWrite()

---

SSDProject/global_config.h
SSDProject/ssd.cpp
SSDProject/ssd.h
SSDProject/ssd_test.cpp

- #82 
- SSD class 및 SSD UT 코드 가독성 향상
- 중복 코드 및 복잡한 동작 함수화
- 상수 값 const 변수로 선언

[#82][TDD_Refactor] tdd refactor output data format fix   refactor

---

TestShell/commandParser.cpp
TestShell/executor.cpp
TestShell/main.cpp
TestShell/ssdApp.cpp

- #93
- [#93] 
- Release build로 동작 확인합니다.

[#93] [Feature] Release build working

---

TestShell/executor.cpp
TestShell/executor.h

- #99
-[#99][feature] read operation using file access
- read operation using file access

[#99][feature] read operation using file access

---

TestShell/commandParser.cpp
TestShell/global_config.h
TestShell/ssdApp.cpp
TestShell/ssdApp.h

- 이 PR이 해결하는 이슈 번호를 적어주세요. 예: `#123`
#106
- [PREFIX] PR 제목을 간결하게 작성해주세요.
- fix read/write command to send to SSD

[#106][Refactor] fix read/write command to send to SSD

---

TestShell/compositExecutor.cpp
TestShell/compositExecutor.h
TestShell/compositExecutor_test.cpp
TestShell/global_config.h

- #113
- [#113][Feature]<<TestScript>> Implement ReadCompare Action
- Test Script 1 ~ 3의 ReadCompare 수행

[#113][Feature]<<TestScript>> Implement ReadCompare Action

---

SSDProject/nand.cpp

- 이 PR이 해결하는 이슈 번호를 적어주세요. 예: `#123` #122
- [PREFIX] PR 제목을 간결하게 작성해주세요. [#122][Bugfix][NAND] ostream의 파일 포멧이 맞지 않는 버그 수정

[#122][Bugfix][NAND] ostream의 파일 포멧이 맞지 않는 버그 수정

---

TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/commandParser.cpp
TestShell/commandParser.h
TestShell/executor.cpp
TestShell/global_config.h
TestShell/shell.cpp
TestShell/ssdApp.cpp
TestShell/ssdApp.h
TestShell/utils.cpp
TestShell/utils.h

- 이 PR이 해결하는 이슈 번호를 적어주세요. 예: `#123`
#123
- [PREFIX] PR 제목을 간결하게 작성해주세요.
utils.h 추가하여 utils에 해당하는 함수 옮김.
clean code 및 #include 정리

[#123][Refactor] clean code and make utils.h

---

TestShell/compositExecutor.cpp
TestShell/executor.cpp

- #137
- [#137][Bugfix] Fix Invalid ReadCompare Action
- ReadCompare 정상 동작

[#137][Bugfix] Fix Invalid ReadCompare Action

---

TestShell/commandParser.cpp
TestShell/compositExecutor.cpp
TestShell/compositExecutor.h
TestShell/compositExecutor_test.cpp
TestShell/executor.cpp
TestShell/executor.h
TestShell/executor_test.cpp
TestShell/interface.h

- #142
- [#142][Refactor] Reorder parameters of execute()
- 
- execute함수의 파라미터 순서 변경

[#142][Refactor] Reorder parameters of execute()

---

TestShell/shell.cpp
TestShell/shellInterface_test.cpp

- #143
- [#143][Bugfix] test_shell: fix result message for tc
- [* ] TestShell

[#143][Bugfix] test_shell: fix result message for tc

---

SSDProject/hostInterface.cpp
SSDProject/hostInterface.h

…수 있도록 interface 처리
- 이 PR이 해결하는 이슈 번호를 적어주세요. 예: `#123` #136 
- [PREFIX] PR 제목을 간결하게 작성해주세요. TestShell에서 들어오는 Erase 및 Flush 처리 Interface 추가

[#136][Feature][HostInterface] TestShell에서 들어오는 Erase 및 Flush 처리 Interface 추가

---

SSDProject/BufferManager.cpp
SSDProject/BufferManager.h
SSDProject/SSDProject.vcxproj
SSDProject/SSDProject.vcxproj.filters
SSDProject/global_config.h
SSDProject/ssd.cpp

- 이 PR이 해결하는 이슈 번호를 적어주세요. 예: `#123` #155 
- [PREFIX] PR 제목을 간결하게 작성해주세요.  Flush 및 Buffer의 File 관련 기본 기능

[#155][Feature] Flush 및 Buffer의 File 관련 기본 기능

---

TestShell/compositExecutor.cpp
TestShell/compositExecutor.h
TestShell/compositExecutor_test.cpp
TestShell/executor.cpp
TestShell/executor.h

- #159 
- [#159][Refactor]Extract Compare from execute of Comparer
- [#159][Refactor]Extract Comparer from ReadCompare()
- [#159][Refactor]Extract Compare from execute of Comparer

[#159][Refactor]Extract Compare from execute of Comparer

---

TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/executor.cpp
TestShell/logger.cpp
TestShell/logger.h

- #127
- [FEATURE] Logger Basic Function 입니다.
- [* ] TestShell
- latest.log에 log정보를 출력합니다.

[#127][feature] testshell: Support logger

---

SSDProject/ssd.cpp
SSDProject/ssd.h

- #170 
- Output File 업데이트 함수 public으로 생성 및 관련 함수 정리

[Feature 구현] Output File 업데이트 함수 public으로 생성

---

TestShell/logger.cpp
TestShell/logger.h

- #165
- [Feature] test_shell: Support ZipLogger & UntilLogger
- test_shell: Support ZipLogger & UntilLogger
User@DESKTOP-5FBE16T MINGW64 /c/work/CCC-SSDProject/TestShell (165-feature-support-to-manage-unitlloggerfile)
$ ls -lah *.log
-rw-r--r-- 1 User 197121 2.6K Jul 31 17:09 latest.log
-rw-r--r-- 1 User 197121  96K Jul 31 17:08 until_20250731_17h_8m_58s.log
-rw-r--r-- 1 User 197121  11K Jul 31 17:09 until_20250731_17h_9m_35s.log
User@DESKTOP-5FBE16T MINGW64 /c/work/CCC-SSDProject/TestShell (165-feature-support-to-manage-unitlloggerfile)
$ ls -lah *.log
-rw-r--r-- 1 User 197121 2.6K Jul 31 17:09 latest.log
-rw-r--r-- 1 User 197121  96K Jul 31 17:08 until_20250731_17h_8m_58s.log
-rw-r--r-- 1 User 197121  11K Jul 31 17:09 until_20250731_17h_9m_35s.log
User@DESKTOP-5FBE16T MINGW64 …

[#165][Feature] test_shell: Support ZipLogger & UntilLogger

---

SSDProject/BufferManager.cpp
SSDProject/BufferManager.h
SSDProject/hostInterface.cpp
SSDProject/hostInterface.h
SSDProject/hostInterface_test.cpp
SSDProject/nand.h

- 이 PR이 해결하는 이슈 번호를 적어주세요. 예: `#123` #161
- [PREFIX] [#161] Dumb Command Buffering 구현
Dumb Command Buffering 구현 합니다. 이 버퍼는 멍청해서 들어온 순서대로 buffer를 기록하고 5개가 차면 flush 진행합니다.

[#161] Dumb Command Buffering 구현

---

SSDProject/global_config.h
SSDProject/hostInterface.cpp
SSDProject/ssd.cpp

- #182 
- ssd 내 HostInterface class에서 추가한 hard coding logging을 TEST_CONFIG로 구성으로 옮겨서 Release에서는 동작 안하도록 수정
- TEST CONFIG 구성에서 출력 동작이 DEBUG_ASSERT로 이동 됐으므로, 따로 cout을 통해 출력할 필요 없다.
- ssd 함수 내에 debugging 출력 define 사용 코드 가독성 좋게 정리

[#182][Refactor] SSD Debugging 용 logging 코드 정리

---

TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/global_config.h
TestShell/main.cpp
TestShell/runner.cpp
TestShell/shell.cpp
TestShell/shell.h
TestShell/utils.cpp
TestShell/utils.h

- #185
- [#185][Feature]<<Runner>> Implement Runner
- 
- [#185][Feature]<<Runner>> define build and release path
- [#185][Feature]<<Runner>> Implement Runner

- [#185][Feature]<<Runner>> Implement Runner

---

.gitignore
SSDProject/SSDProject.vcxproj.user
TestShell/TestShell.vcxproj.user
TestShell/global_config.h

- #194
- [BugFix] fix build system and .gitignore
.gitignore 에서 *.user 삭제
/SSDProject/SSDProject.vcxproj.user 작업 디렉토리 수정
/TestShell/TestShell.vcxproj.user 작업 디렉토리 수정

[#194][BugFix] fix build system and .gitignore

---

SSDProject/BufferManager.cpp
SSDProject/BufferManager.h
SSDProject/hostInterface.cpp

- 이 PR이 해결하는 이슈 번호를 적어주세요. 예: `#123` #181
- [PREFIX] PR 제목을 간결하게 작성해주세요. Algorithm 을 사용한 Command Buffer 최적화
- 변경된 내용을 요약해주세요. ConveryBufToCmd 가 핵심 알고리즘입니다. 리팩토링은 진행하겠습니다.

[#181][Feature][SSD] Algorithm 을 사용한 Command Buffer 최적화

---

SSDProject/BufferManager.cpp

- 이 PR이 해결하는 이슈 번호를 적어주세요. 예: `#123` #199
- [PREFIX] PR 제목을 간결하게 작성해주세요. DEBUG 옵션 버그 수정 (Buffer Manager)

[#199][Bugfix] DEBUG 옵션 버그 수정

---

TestShell/executor.cpp
TestShell/executor.h
TestShell/global_config.h
TestShell/interface.h

- #205 
- [#205][Refactor] Separate Eraser Class
- [#205][Refactor] Separate Eraser Class

- [#205][Refactor] Separate Eraser Class

---

TestShell/commandParser.cpp
TestShell/commandParser.h
TestShell/commandParser_test.cpp
TestShell/compositExecutor.cpp
TestShell/executor.cpp
TestShell/executor.h
TestShell/global_config.h
TestShell/runner.cpp
TestShell/shellInterface_test.cpp
TestShell/ssdApp.cpp
TestShell/utils.cpp
TestShell/utils.h

- #190
- [PREFIX] PR 제목을 간결하게 작성해주세요.
- TestShellUtils class를 만들고 내부 멤버함수는 static 함수로 구성했습니다.
- print함수만 일반 전역함수로 뒀습니다.
- dbgPring도 추가했습니다.

[#190][Refactor] make TestShellUtils class

---

SSDProject/BufferedSSD.cpp

- 이 PR이 해결하는 이슈 번호를 적어주세요. 예: `#123` #227 
- [PREFIX] [#227][Bugfix] Buffer 구조 Refactoring 및 버그 수정

[#227][Bugfix] Buffer 구조 Refactoring 및 버그 수정

---

TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/commandParser.h
TestShell/commandParser_test.cpp
TestShell/compositeExecutor.h
TestShell/compositeExecutor_test.cpp
TestShell/executorFactory.cpp
TestShell/executorFactory.h
TestShell/executor_test.cpp
TestShell/interface.h
TestShell/runner.cpp
TestShell/shell.cpp

- #239 
- [#239][Refactoring] Implement CachedExecutorFactory
- CachedExecutorFactory 추출

[#239][Refactoring] Implement CachedExecutorFactory

---

TestShell/compositeExecutor_test.cpp
TestShell/executorFactory.cpp
TestShell/executorFactory.h
TestShell/shell.cpp

- #242 
- #243 
- [#242][Refactor] Implement DelegatedExecutorFactory
- [#243][Bugfix] Re-enable UT to use shared_ptr
- [#242][Refactor] Implement DelegatedExecutorFactory

[#242][Refactor] Implement DelegatedExecutorFactory

---

TestShell/compositeExecutor.cpp
TestShell/compositeExecutor.h
TestShell/compositeExecutor_test.cpp
TestShell/executorFactory.cpp
TestShell/executorFactory.h
TestShell/runner.cpp

- #246 
- [#246][Refactor] Implement ICompositeExecutorStrategy
-  [#246][Refactor] Implement ICompositeExecutorStrategy

[#246][Refactor] Implement ICompositeExecutorStrategy

---

TestShell/commandParser.h
TestShell/commandParser_test.cpp
TestShell/compositeExecutor.h
TestShell/runner.cpp
TestShell/shell.cpp
TestShell/shell.h
TestShell/shellInterface_test.cpp

- #245
- [#245][refactor] no more use direct pointer
- [#245][refactor] no more use direct pointer

[#245][refactor] no more use direct pointer
